
debug: false
#management.endpoints.web.exposure.include: "*"

logging:
  level:
    Neuroflow.project: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.security: debug

spring:
  datasource:
    url: jdbc:mariadb://13.209.105.14:3306/neuroflow?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: 'JCH'
    password: 'neuroflow12'
    driverClassName: org.mariadb.jdbc.Driver

cloud:
  aws:
    s3:
      bucket: dev-team12-wannabe-image
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: AKIAT2424X6ELPQIKNEF
      secretKey: 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