
debug: false
#management.endpoints.web.exposure.include: "*"

logging:
  level:
    Neuroflow.project: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.security: debug

spring:
  datasource:
    url: jdbc:mariadb://13.209.105.14:3306/test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: 'JCH'
    password: 'neuroflow12'
    driverClassName: org.mariadb.jdbc.Driver