
debug: false
#management.endpoints.web.exposure.include: "*"

logging:
  level:
    Neuroflow.project: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.security: debug

spring:
  datasource:
    url: jdbc:mariadb://13.209.105.14:3306/neuroflow?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: 'JCH'
    password: 'neuroflow12'
    driverClassName: org.mariadb.jdbc.Driver
#  servlet:
#    multipart:
#      enabled: true # 멀티파트 업로드 지원여부 (default: true)
#      file-size-threshold: 0B # 파일을 디스크에 저장하지 않고 메모리에 저장하는 최소 크기 (default: 0B)
##      location: /users/charming/temp # 업로드된 파일이 임시로 저장되는 디스크 위치 (default: WAS가 결정)
#      max-file-size: 100MB # 한개 파일의 최대 사이즈 (default: 1MB)
#      max-request-size: 100MB # 한개 요청의 최대 사이즈 (default: 10MB)

cloud:
  aws:
    s3:
      bucket: dev-team12-client-image
    stack.auto: false

    region.static: ap-northeast-2
    credentials:
      accessKey: "AKIAT2424X6EG27BAXW5"
      secretKey: "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"

